# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/opt/conda/envs/ml-zoomcamp/lib/python3.11/site-packages/numpy/__init__.py'>

## Creating arrays


In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [8]:
a[2]

np.int64(3)

In [9]:
a[2] = 10

In [10]:
a

array([ 1,  2, 10,  5,  7, 12])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional arrays


In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
    

In [16]:
n[0,1]

np.int64(2)

In [17]:
n[0,1] = 20

In [18]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [19]:
n[0]

array([ 1, 20,  3])

In [20]:
n[2] = [1,1,1]

In [21]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
n[:,2]

array([3, 6, 1])

In [23]:
n[:,2] = [0,1,2]

In [24]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays


In [27]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [28]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [29]:
np.random.seed(2)
100*np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
a + 1

array([1, 2, 3, 4, 5])

In [34]:
a * 2

array([0, 2, 4, 6, 8])

In [38]:
b = (10 + (a*2)) ** 2 /100

In [40]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [39]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [41]:
a / b +10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [42]:
a

array([0, 1, 2, 3, 4])

In [43]:
a >= 2

array([False, False,  True,  True,  True])

In [45]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [44]:
a > b

array([False, False,  True,  True,  True])

In [46]:
a[a > b]

array([2, 3, 4])

array([2, 3, 4])

## Summarizing operations

In [47]:
a

array([0, 1, 2, 3, 4])

In [48]:
a.min()

np.int64(0)

In [49]:
a.max()

np.int64(4)

In [50]:
a.sum()

np.int64(10)

In [51]:
a.mean()

np.float64(2.0)

In [52]:
a.std()

np.float64(1.4142135623730951)

### Next

Linear algebra refresher